// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: AggregateProof.proto

package V1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Height struct {
	// the revision that the client is currently on
	RevisionNumber uint64 `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	// the height within the given revision
	RevisionHeight       uint64   `protobuf:"varint,2,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Height) Reset()         { *m = Height{} }
func (m *Height) String() string { return proto.CompactTextString(m) }
func (*Height) ProtoMessage()    {}
func (*Height) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{0}
}
func (m *Height) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Height.Unmarshal(m, b)
}
func (m *Height) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Height.Marshal(b, m, deterministic)
}
func (m *Height) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Height.Merge(m, src)
}
func (m *Height) XXX_Size() int {
	return xxx_messageInfo_Height.Size(m)
}
func (m *Height) XXX_DiscardUnknown() {
	xxx_messageInfo_Height.DiscardUnknown(m)
}

var xxx_messageInfo_Height proto.InternalMessageInfo

func (m *Height) GetRevisionNumber() uint64 {
	if m != nil {
		return m.RevisionNumber
	}
	return 0
}

func (m *Height) GetRevisionHeight() uint64 {
	if m != nil {
		return m.RevisionHeight
	}
	return 0
}

type Packet struct {
	// number corresponds to the order of sends and receives, where a Packet
	// with an earlier sequence number must be sent and received before a Packet
	// with a later sequence number.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// identifies the port on the sending chain.
	SourcePort string `protobuf:"bytes,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// identifies the channel end on the sending chain.
	SourceChannel string `protobuf:"bytes,3,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	// identifies the port on the receiving chain.
	DestinationPort string `protobuf:"bytes,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	// identifies the channel end on the receiving chain.
	DestinationChannel string `protobuf:"bytes,5,opt,name=destination_channel,json=destinationChannel,proto3" json:"destination_channel,omitempty"`
	// actual opaque bytes transferred directly to the application module
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// block height after which the packet times out
	TimeoutHeight *Height `protobuf:"bytes,7,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height,omitempty"`
	// block timestamp (in nanoseconds) after which the packet times out
	TimeoutTimestamp     uint64   `protobuf:"varint,8,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{1}
}
func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Packet) GetSourcePort() string {
	if m != nil {
		return m.SourcePort
	}
	return ""
}

func (m *Packet) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

func (m *Packet) GetDestinationPort() string {
	if m != nil {
		return m.DestinationPort
	}
	return ""
}

func (m *Packet) GetDestinationChannel() string {
	if m != nil {
		return m.DestinationChannel
	}
	return ""
}

func (m *Packet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Packet) GetTimeoutHeight() *Height {
	if m != nil {
		return m.TimeoutHeight
	}
	return nil
}

func (m *Packet) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

type InnerOp struct {
	Prefix               []byte   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix               []byte   `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerOp) Reset()         { *m = InnerOp{} }
func (m *InnerOp) String() string { return proto.CompactTextString(m) }
func (*InnerOp) ProtoMessage()    {}
func (*InnerOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{2}
}
func (m *InnerOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerOp.Unmarshal(m, b)
}
func (m *InnerOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerOp.Marshal(b, m, deterministic)
}
func (m *InnerOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerOp.Merge(m, src)
}
func (m *InnerOp) XXX_Size() int {
	return xxx_messageInfo_InnerOp.Size(m)
}
func (m *InnerOp) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerOp.DiscardUnknown(m)
}

var xxx_messageInfo_InnerOp proto.InternalMessageInfo

func (m *InnerOp) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *InnerOp) GetSuffix() []byte {
	if m != nil {
		return m.Suffix
	}
	return nil
}

type ProofMeta struct {
	PathInnerOp          *InnerOp `protobuf:"bytes,1,opt,name=path_inner_op,json=pathInnerOp,proto3" json:"path_inner_op,omitempty"`
	HashValue            [][]byte `protobuf:"bytes,2,rep,name=hash_value,json=hashValue,proto3" json:"hash_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofMeta) Reset()         { *m = ProofMeta{} }
func (m *ProofMeta) String() string { return proto.CompactTextString(m) }
func (*ProofMeta) ProtoMessage()    {}
func (*ProofMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{3}
}
func (m *ProofMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofMeta.Unmarshal(m, b)
}
func (m *ProofMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofMeta.Marshal(b, m, deterministic)
}
func (m *ProofMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofMeta.Merge(m, src)
}
func (m *ProofMeta) XXX_Size() int {
	return xxx_messageInfo_ProofMeta.Size(m)
}
func (m *ProofMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ProofMeta proto.InternalMessageInfo

func (m *ProofMeta) GetPathInnerOp() *InnerOp {
	if m != nil {
		return m.PathInnerOp
	}
	return nil
}

func (m *ProofMeta) GetHashValue() [][]byte {
	if m != nil {
		return m.HashValue
	}
	return nil
}

type SubProof struct {
	Number               uint32       `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	ProofMetaList        []*ProofMeta `protobuf:"bytes,2,rep,name=proof_meta_list,json=proofMetaList,proto3" json:"proof_meta_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SubProof) Reset()         { *m = SubProof{} }
func (m *SubProof) String() string { return proto.CompactTextString(m) }
func (*SubProof) ProtoMessage()    {}
func (*SubProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{4}
}
func (m *SubProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubProof.Unmarshal(m, b)
}
func (m *SubProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubProof.Marshal(b, m, deterministic)
}
func (m *SubProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubProof.Merge(m, src)
}
func (m *SubProof) XXX_Size() int {
	return xxx_messageInfo_SubProof.Size(m)
}
func (m *SubProof) XXX_DiscardUnknown() {
	xxx_messageInfo_SubProof.DiscardUnknown(m)
}

var xxx_messageInfo_SubProof proto.InternalMessageInfo

func (m *SubProof) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SubProof) GetProofMetaList() []*ProofMeta {
	if m != nil {
		return m.ProofMetaList
	}
	return nil
}

type AggregatePacket struct {
	Proof                []*SubProof `protobuf:"bytes,1,rep,name=proof,proto3" json:"proof,omitempty"`
	Signer               string      `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	Packets              []*Packet   `protobuf:"bytes,3,rep,name=packets,proto3" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AggregatePacket) Reset()         { *m = AggregatePacket{} }
func (m *AggregatePacket) String() string { return proto.CompactTextString(m) }
func (*AggregatePacket) ProtoMessage()    {}
func (*AggregatePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{5}
}
func (m *AggregatePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatePacket.Unmarshal(m, b)
}
func (m *AggregatePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatePacket.Marshal(b, m, deterministic)
}
func (m *AggregatePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatePacket.Merge(m, src)
}
func (m *AggregatePacket) XXX_Size() int {
	return xxx_messageInfo_AggregatePacket.Size(m)
}
func (m *AggregatePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatePacket.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatePacket proto.InternalMessageInfo

func (m *AggregatePacket) GetProof() []*SubProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *AggregatePacket) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *AggregatePacket) GetPackets() []*Packet {
	if m != nil {
		return m.Packets
	}
	return nil
}

func init() {
	proto.RegisterType((*Height)(nil), "ibc.lightclients.zkp.v1.Height")
	proto.RegisterType((*Packet)(nil), "ibc.lightclients.zkp.v1.Packet")
	proto.RegisterType((*InnerOp)(nil), "ibc.lightclients.zkp.v1.InnerOp")
	proto.RegisterType((*ProofMeta)(nil), "ibc.lightclients.zkp.v1.ProofMeta")
	proto.RegisterType((*SubProof)(nil), "ibc.lightclients.zkp.v1.SubProof")
	proto.RegisterType((*AggregatePacket)(nil), "ibc.lightclients.zkp.v1.AggregatePacket")
}

func init() { proto.RegisterFile("AggregateProof.proto", fileDescriptor_eaa420b1aacb1d8d) }

var fileDescriptor_eaa420b1aacb1d8d = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x86, 0x95, 0x4e, 0xa7, 0x97, 0xd3, 0xdb, 0x60, 0x10, 0x44, 0x48, 0x68, 0x4a, 0x24, 0x44,
	0x11, 0x52, 0xd0, 0x94, 0x05, 0x9a, 0x25, 0x17, 0x21, 0x40, 0x5c, 0x2a, 0x83, 0x66, 0x31, 0x9b,
	0xc8, 0xcd, 0x9c, 0x36, 0xd6, 0xb4, 0x8e, 0xb1, 0x9d, 0x0a, 0xf1, 0x2e, 0x3c, 0x14, 0x6f, 0x84,
	0x7c, 0x9c, 0x0c, 0x9d, 0x45, 0x57, 0xf1, 0xf9, 0xfd, 0xfb, 0xf3, 0xc9, 0x9f, 0x13, 0xb8, 0xf7,
	0x7a, 0xbd, 0x36, 0xb8, 0x16, 0x0e, 0x17, 0xa6, 0x2c, 0x57, 0xa9, 0x36, 0xa5, 0x2b, 0xd9, 0x03,
	0xb9, 0xcc, 0xd3, 0x8d, 0x5c, 0x17, 0x2e, 0xdf, 0x48, 0x54, 0xce, 0xa6, 0xbf, 0xaf, 0x75, 0xba,
	0x3b, 0x4b, 0x2e, 0xa1, 0xf3, 0x01, 0xbd, 0xce, 0x9e, 0xc2, 0xc4, 0xe0, 0x4e, 0x5a, 0x59, 0xaa,
	0x4c, 0x55, 0xdb, 0x25, 0x9a, 0x38, 0x9a, 0x46, 0xb3, 0x36, 0x1f, 0x37, 0xf2, 0x57, 0x52, 0x6f,
	0x19, 0x0b, 0x3a, 0x1b, 0xb7, 0x6e, 0x1b, 0x03, 0x31, 0xf9, 0xdb, 0x82, 0xce, 0x42, 0xe4, 0xd7,
	0xe8, 0xd8, 0x43, 0xe8, 0x59, 0xfc, 0x59, 0xa1, 0xca, 0xb1, 0xa6, 0xde, 0xd4, 0xec, 0x14, 0x06,
	0xb6, 0xac, 0x4c, 0x8e, 0x99, 0x2e, 0x4d, 0x60, 0xf5, 0x39, 0x04, 0x69, 0x51, 0x1a, 0xc7, 0x9e,
	0xc0, 0xb8, 0x36, 0xe4, 0x85, 0x50, 0x0a, 0x37, 0xf1, 0x11, 0x79, 0x46, 0x41, 0x7d, 0x1b, 0x44,
	0xf6, 0x0c, 0x4e, 0xae, 0xd0, 0x3a, 0xa9, 0x84, 0xf3, 0xad, 0x11, 0xac, 0x4d, 0xc6, 0xc9, 0x9e,
	0x4e, 0xc4, 0x17, 0x70, 0x77, 0xdf, 0xda, 0x60, 0x8f, 0xc9, 0xcd, 0xf6, 0xb6, 0x1a, 0x36, 0x83,
	0xf6, 0x95, 0x70, 0x22, 0xee, 0x4c, 0xa3, 0xd9, 0x90, 0xd3, 0x9a, 0xbd, 0x87, 0xb1, 0x93, 0x5b,
	0x2c, 0x2b, 0xd7, 0xc4, 0xd0, 0x9d, 0x46, 0xb3, 0xc1, 0xfc, 0x34, 0x3d, 0x10, 0x76, 0x1a, 0x72,
	0xe1, 0xa3, 0xfa, 0x58, 0x1d, 0xfc, 0x73, 0xb8, 0xd3, 0x70, 0xfc, 0xd3, 0x3a, 0xb1, 0xd5, 0x71,
	0x8f, 0x42, 0x3a, 0xa9, 0x37, 0x7e, 0x34, 0x7a, 0x72, 0x0e, 0xdd, 0x8f, 0x4a, 0xa1, 0xf9, 0xa6,
	0xd9, 0x7d, 0xe8, 0x68, 0x83, 0x2b, 0xf9, 0x8b, 0x12, 0x1d, 0xf2, 0xba, 0xf2, 0xba, 0xad, 0x56,
	0x5e, 0x6f, 0x05, 0x3d, 0x54, 0x89, 0x86, 0x3e, 0x8d, 0xc4, 0x17, 0x74, 0x82, 0xbd, 0x83, 0x91,
	0x16, 0xae, 0xc8, 0xa4, 0x87, 0x65, 0xa5, 0x26, 0xc6, 0x60, 0x3e, 0x3d, 0xd8, 0x7b, 0x7d, 0x2b,
	0x1f, 0xf8, 0x63, 0x4d, 0x0b, 0x8f, 0x00, 0x0a, 0x61, 0x8b, 0x6c, 0x27, 0x36, 0x15, 0xc6, 0xad,
	0xe9, 0xd1, 0x6c, 0xc8, 0xfb, 0x5e, 0xb9, 0xf0, 0x42, 0xa2, 0xa0, 0xf7, 0xbd, 0x5a, 0xd2, 0xa5,
	0xbe, 0xab, 0xbd, 0xa9, 0x1a, 0xf1, 0xba, 0x62, 0x9f, 0x60, 0xa2, 0xbd, 0x21, 0xdb, 0xa2, 0x13,
	0xd9, 0x46, 0x5a, 0x47, 0x9c, 0xc1, 0x3c, 0x39, 0xd8, 0xca, 0xcd, 0x5b, 0xf0, 0x91, 0x6e, 0x96,
	0x9f, 0xa5, 0x75, 0xc9, 0x9f, 0x08, 0x26, 0xff, 0xc7, 0x3f, 0x4c, 0xde, 0x2b, 0x38, 0x26, 0x53,
	0x1c, 0x11, 0xf5, 0xf1, 0x41, 0x6a, 0xd3, 0x29, 0x0f, 0x7e, 0x8a, 0x51, 0xae, 0x15, 0x9a, 0x7a,
	0x22, 0xeb, 0x8a, 0x9d, 0x43, 0x57, 0x13, 0xda, 0xc6, 0x47, 0x84, 0x3c, 0xfc, 0xbd, 0x43, 0x0b,
	0xbc, 0xf1, 0xbf, 0x69, 0x5f, 0xb6, 0x2e, 0xce, 0x96, 0x1d, 0xfa, 0x25, 0x5f, 0xfe, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xa4, 0xf1, 0x56, 0x82, 0xaa, 0x03, 0x00, 0x00,
}
