// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: AggregateProof.proto

package aggrelite

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HashOp int32

const (
	// NO_HASH is the default if no data passed. Note this is an illegal argument some places.
	HashOp_NO_HASH     HashOp = 0
	HashOp_SHA256      HashOp = 1
	HashOp_SHA512      HashOp = 2
	HashOp_KECCAK256   HashOp = 3
	HashOp_RIPEMD160   HashOp = 4
	HashOp_BITCOIN     HashOp = 5
	HashOp_SHA512_256  HashOp = 6
	HashOp_BLAKE2B_512 HashOp = 7
	HashOp_BLAKE2S_256 HashOp = 8
	HashOp_BLAKE3      HashOp = 9
)

var HashOp_name = map[int32]string{
	0: "NO_HASH",
	1: "SHA256",
	2: "SHA512",
	3: "KECCAK256",
	4: "RIPEMD160",
	5: "BITCOIN",
	6: "SHA512_256",
	7: "BLAKE2B_512",
	8: "BLAKE2S_256",
	9: "BLAKE3",
}

var HashOp_value = map[string]int32{
	"NO_HASH":     0,
	"SHA256":      1,
	"SHA512":      2,
	"KECCAK256":   3,
	"RIPEMD160":   4,
	"BITCOIN":     5,
	"SHA512_256":  6,
	"BLAKE2B_512": 7,
	"BLAKE2S_256": 8,
	"BLAKE3":      9,
}

func (x HashOp) String() string {
	return proto.EnumName(HashOp_name, int32(x))
}

func (HashOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{0}
}

type Height struct {
	// the revision that the client is currently on
	RevisionNumber uint64 `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	// the height within the given revision
	RevisionHeight       uint64   `protobuf:"varint,2,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Height) Reset()         { *m = Height{} }
func (m *Height) String() string { return proto.CompactTextString(m) }
func (*Height) ProtoMessage()    {}
func (*Height) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{0}
}
func (m *Height) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Height.Unmarshal(m, b)
}
func (m *Height) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Height.Marshal(b, m, deterministic)
}
func (m *Height) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Height.Merge(m, src)
}
func (m *Height) XXX_Size() int {
	return xxx_messageInfo_Height.Size(m)
}
func (m *Height) XXX_DiscardUnknown() {
	xxx_messageInfo_Height.DiscardUnknown(m)
}

var xxx_messageInfo_Height proto.InternalMessageInfo

func (m *Height) GetRevisionNumber() uint64 {
	if m != nil {
		return m.RevisionNumber
	}
	return 0
}

func (m *Height) GetRevisionHeight() uint64 {
	if m != nil {
		return m.RevisionHeight
	}
	return 0
}

type Packet struct {
	// number corresponds to the order of sends and receives, where a Packet
	// with an earlier sequence number must be sent and received before a Packet
	// with a later sequence number.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// identifies the port on the sending chain.
	SourcePort string `protobuf:"bytes,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// identifies the channel end on the sending chain.
	SourceChannel string `protobuf:"bytes,3,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	// identifies the port on the receiving chain.
	DestinationPort string `protobuf:"bytes,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	// identifies the channel end on the receiving chain.
	DestinationChannel string `protobuf:"bytes,5,opt,name=destination_channel,json=destinationChannel,proto3" json:"destination_channel,omitempty"`
	// actual opaque bytes transferred directly to the application module
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// block height after which the packet times out
	TimeoutHeight *Height `protobuf:"bytes,7,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height,omitempty"`
	// block timestamp (in nanoseconds) after which the packet times out
	TimeoutTimestamp     uint64   `protobuf:"varint,8,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{1}
}
func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Packet) GetSourcePort() string {
	if m != nil {
		return m.SourcePort
	}
	return ""
}

func (m *Packet) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

func (m *Packet) GetDestinationPort() string {
	if m != nil {
		return m.DestinationPort
	}
	return ""
}

func (m *Packet) GetDestinationChannel() string {
	if m != nil {
		return m.DestinationChannel
	}
	return ""
}

func (m *Packet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Packet) GetTimeoutHeight() *Height {
	if m != nil {
		return m.TimeoutHeight
	}
	return nil
}

func (m *Packet) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

// 仍需修改
type InnerOp struct {
	Hash                 HashOp   `protobuf:"varint,1,opt,name=hash,proto3,enum=ibc.lightclients.aggrelite.HashOp" json:"hash,omitempty"`
	Prefix               []byte   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix               []byte   `protobuf:"bytes,3,opt,name=suffix,proto3" json:"suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerOp) Reset()         { *m = InnerOp{} }
func (m *InnerOp) String() string { return proto.CompactTextString(m) }
func (*InnerOp) ProtoMessage()    {}
func (*InnerOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{2}
}
func (m *InnerOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerOp.Unmarshal(m, b)
}
func (m *InnerOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerOp.Marshal(b, m, deterministic)
}
func (m *InnerOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerOp.Merge(m, src)
}
func (m *InnerOp) XXX_Size() int {
	return xxx_messageInfo_InnerOp.Size(m)
}
func (m *InnerOp) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerOp.DiscardUnknown(m)
}

var xxx_messageInfo_InnerOp proto.InternalMessageInfo

func (m *InnerOp) GetHash() HashOp {
	if m != nil {
		return m.Hash
	}
	return HashOp_NO_HASH
}

func (m *InnerOp) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *InnerOp) GetSuffix() []byte {
	if m != nil {
		return m.Suffix
	}
	return nil
}

type ProofMeta struct {
	HashValue            []byte   `protobuf:"bytes,1,opt,name=hash_value,json=hashValue,proto3" json:"hash_value,omitempty"`
	PathInnerOp          *InnerOp `protobuf:"bytes,2,opt,name=path_inner_op,json=pathInnerOp,proto3" json:"path_inner_op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofMeta) Reset()         { *m = ProofMeta{} }
func (m *ProofMeta) String() string { return proto.CompactTextString(m) }
func (*ProofMeta) ProtoMessage()    {}
func (*ProofMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{3}
}
func (m *ProofMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofMeta.Unmarshal(m, b)
}
func (m *ProofMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofMeta.Marshal(b, m, deterministic)
}
func (m *ProofMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofMeta.Merge(m, src)
}
func (m *ProofMeta) XXX_Size() int {
	return xxx_messageInfo_ProofMeta.Size(m)
}
func (m *ProofMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ProofMeta proto.InternalMessageInfo

func (m *ProofMeta) GetHashValue() []byte {
	if m != nil {
		return m.HashValue
	}
	return nil
}

func (m *ProofMeta) GetPathInnerOp() *InnerOp {
	if m != nil {
		return m.PathInnerOp
	}
	return nil
}

type SubProof struct {
	Number               uint32       `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	ProofMetaList        []*ProofMeta `protobuf:"bytes,2,rep,name=proof_meta_list,json=proofMetaList,proto3" json:"proof_meta_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SubProof) Reset()         { *m = SubProof{} }
func (m *SubProof) String() string { return proto.CompactTextString(m) }
func (*SubProof) ProtoMessage()    {}
func (*SubProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{4}
}
func (m *SubProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubProof.Unmarshal(m, b)
}
func (m *SubProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubProof.Marshal(b, m, deterministic)
}
func (m *SubProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubProof.Merge(m, src)
}
func (m *SubProof) XXX_Size() int {
	return xxx_messageInfo_SubProof.Size(m)
}
func (m *SubProof) XXX_DiscardUnknown() {
	xxx_messageInfo_SubProof.DiscardUnknown(m)
}

var xxx_messageInfo_SubProof proto.InternalMessageInfo

func (m *SubProof) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SubProof) GetProofMetaList() []*ProofMeta {
	if m != nil {
		return m.ProofMetaList
	}
	return nil
}

type AggregatePacket struct {
	Packets              []*Packet   `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	PacketsLeafNumber    []uint32    `protobuf:"varint,2,rep,packed,name=packets_leaf_number,json=packetsLeafNumber,proto3" json:"packets_leaf_number,omitempty"`
	Proof                []*SubProof `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
	Signer               string      `protobuf:"bytes,4,opt,name=signer,proto3" json:"signer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AggregatePacket) Reset()         { *m = AggregatePacket{} }
func (m *AggregatePacket) String() string { return proto.CompactTextString(m) }
func (*AggregatePacket) ProtoMessage()    {}
func (*AggregatePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa420b1aacb1d8d, []int{5}
}
func (m *AggregatePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatePacket.Unmarshal(m, b)
}
func (m *AggregatePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatePacket.Marshal(b, m, deterministic)
}
func (m *AggregatePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatePacket.Merge(m, src)
}
func (m *AggregatePacket) XXX_Size() int {
	return xxx_messageInfo_AggregatePacket.Size(m)
}
func (m *AggregatePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatePacket.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatePacket proto.InternalMessageInfo

func (m *AggregatePacket) GetPackets() []*Packet {
	if m != nil {
		return m.Packets
	}
	return nil
}

func (m *AggregatePacket) GetPacketsLeafNumber() []uint32 {
	if m != nil {
		return m.PacketsLeafNumber
	}
	return nil
}

func (m *AggregatePacket) GetProof() []*SubProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *AggregatePacket) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func init() {
	proto.RegisterEnum("ibc.lightclients.aggrelite.HashOp", HashOp_name, HashOp_value)
	proto.RegisterType((*Height)(nil), "ibc.lightclients.aggrelite.Height")
	proto.RegisterType((*Packet)(nil), "ibc.lightclients.aggrelite.Packet")
	proto.RegisterType((*InnerOp)(nil), "ibc.lightclients.aggrelite.InnerOp")
	proto.RegisterType((*ProofMeta)(nil), "ibc.lightclients.aggrelite.ProofMeta")
	proto.RegisterType((*SubProof)(nil), "ibc.lightclients.aggrelite.SubProof")
	proto.RegisterType((*AggregatePacket)(nil), "ibc.lightclients.aggrelite.AggregatePacket")
}

func init() { proto.RegisterFile("AggregateProof.proto", fileDescriptor_eaa420b1aacb1d8d) }

var fileDescriptor_eaa420b1aacb1d8d = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x4d, 0xea, 0x24, 0xe3, 0x3a, 0x71, 0xb7, 0x08, 0x59, 0x95, 0x10, 0x95, 0xa1, 0x22,
	0x80, 0x14, 0x68, 0xaa, 0xf6, 0x80, 0xb8, 0x24, 0xa1, 0x22, 0x51, 0x7f, 0x12, 0x6d, 0x2a, 0x0e,
	0xbd, 0x58, 0x9b, 0x74, 0x13, 0xaf, 0x70, 0x6c, 0xd7, 0xbb, 0xae, 0x78, 0x12, 0x5e, 0x0c, 0x1e,
	0x08, 0xed, 0x8f, 0xdb, 0xf4, 0x40, 0x38, 0x79, 0xe6, 0x9b, 0x6f, 0xbe, 0x99, 0x9d, 0x9d, 0x35,
	0x3c, 0xef, 0x2d, 0x97, 0x39, 0x5d, 0x12, 0x41, 0x27, 0x79, 0x9a, 0x2e, 0x3a, 0x59, 0x9e, 0x8a,
	0x14, 0xed, 0xb3, 0xd9, 0xbc, 0x13, 0xb3, 0x65, 0x24, 0xe6, 0x31, 0xa3, 0x89, 0xe0, 0x1d, 0x22,
	0x69, 0x31, 0x13, 0x34, 0xb8, 0x01, 0x7b, 0x48, 0x65, 0x08, 0xbd, 0x85, 0x56, 0x4e, 0xef, 0x19,
	0x67, 0x69, 0x12, 0x26, 0xc5, 0x6a, 0x46, 0x73, 0xdf, 0x3a, 0xb0, 0xda, 0x55, 0xdc, 0x2c, 0xe1,
	0x2b, 0x85, 0x3e, 0x21, 0x46, 0x2a, 0xd7, 0xdf, 0x7a, 0x4a, 0xd4, 0x8a, 0xc1, 0x9f, 0x2d, 0xb0,
	0x27, 0x64, 0xfe, 0x83, 0x0a, 0xb4, 0x0f, 0x75, 0x4e, 0xef, 0x0a, 0x9a, 0xcc, 0xa9, 0x51, 0x7d,
	0xf0, 0xd1, 0x2b, 0x70, 0x78, 0x5a, 0xe4, 0x73, 0x1a, 0x66, 0x69, 0xae, 0xb5, 0x1a, 0x18, 0x34,
	0x34, 0x49, 0x73, 0x81, 0x0e, 0xa1, 0x69, 0x08, 0xf3, 0x88, 0x24, 0x09, 0x8d, 0xfd, 0x8a, 0xe2,
	0xb8, 0x1a, 0x1d, 0x68, 0x10, 0xbd, 0x03, 0xef, 0x96, 0x72, 0xc1, 0x12, 0x22, 0x64, 0x6b, 0x4a,
	0xac, 0xaa, 0x88, 0xad, 0x35, 0x5c, 0x29, 0x7e, 0x84, 0xbd, 0x75, 0x6a, 0x29, 0xbb, 0xad, 0xd8,
	0x68, 0x2d, 0x54, 0x6a, 0x23, 0xa8, 0xde, 0x12, 0x41, 0x7c, 0xfb, 0xc0, 0x6a, 0xef, 0x60, 0x65,
	0xa3, 0x11, 0x34, 0x05, 0x5b, 0xd1, 0xb4, 0x10, 0xe5, 0x18, 0x6a, 0x07, 0x56, 0xdb, 0xe9, 0x06,
	0x9d, 0x7f, 0xcf, 0xbb, 0xa3, 0x47, 0x83, 0x5d, 0x93, 0x69, 0x66, 0xff, 0x01, 0x76, 0x4b, 0x29,
	0xf9, 0xe5, 0x82, 0xac, 0x32, 0xbf, 0xae, 0xe6, 0xe4, 0x99, 0xc0, 0x75, 0x89, 0x07, 0x77, 0x50,
	0x1b, 0x25, 0x09, 0xcd, 0xc7, 0x19, 0x3a, 0x85, 0x6a, 0x44, 0x78, 0xa4, 0x46, 0xda, 0xfc, 0x4f,
	0x61, 0xc2, 0xa3, 0x71, 0x86, 0x15, 0x1f, 0xbd, 0x00, 0x3b, 0xcb, 0xe9, 0x82, 0xfd, 0x54, 0xd3,
	0xde, 0xc1, 0xc6, 0x93, 0x38, 0x2f, 0x16, 0x12, 0xaf, 0x68, 0x5c, 0x7b, 0x01, 0x87, 0x86, 0x5a,
	0xa8, 0x4b, 0x2a, 0x08, 0x7a, 0x09, 0x20, 0x45, 0xc2, 0x7b, 0x12, 0x17, 0xfa, 0x36, 0x77, 0x70,
	0x43, 0x22, 0xdf, 0x25, 0x80, 0xbe, 0x81, 0x9b, 0x11, 0x11, 0x85, 0x4c, 0xf6, 0x18, 0xa6, 0x99,
	0x2a, 0xe1, 0x74, 0x5f, 0x6f, 0x6a, 0xce, 0x9c, 0x07, 0x3b, 0x32, 0xd3, 0x38, 0xc1, 0x1d, 0xd4,
	0xa7, 0xc5, 0x4c, 0xd5, 0x95, 0x8d, 0xad, 0xed, 0xa4, 0x8b, 0x8d, 0x87, 0x2e, 0xa1, 0x95, 0x49,
	0x42, 0xb8, 0xa2, 0x82, 0x84, 0x31, 0xe3, 0x72, 0x7f, 0x2a, 0x6d, 0xa7, 0x7b, 0xb8, 0xa9, 0xdc,
	0xc3, 0x59, 0xb0, 0x9b, 0x95, 0xe6, 0x05, 0xe3, 0x22, 0xf8, 0x6d, 0x41, 0xeb, 0xf1, 0x09, 0xe9,
	0xd5, 0xfd, 0x02, 0xb5, 0x4c, 0x59, 0xdc, 0xb7, 0x94, 0xf4, 0xc6, 0x31, 0xeb, 0x24, 0x5c, 0xa6,
	0xa0, 0x0e, 0xec, 0x19, 0x33, 0x8c, 0x29, 0x59, 0x94, 0x2f, 0x4b, 0x36, 0xe9, 0xe2, 0x5d, 0x13,
	0xba, 0xa0, 0x64, 0x61, 0x1e, 0xd7, 0x67, 0xd8, 0x56, 0x2d, 0xf9, 0x15, 0x55, 0xeb, 0xcd, 0xa6,
	0x5a, 0xe5, 0x74, 0xb0, 0x4e, 0x51, 0xb7, 0xc7, 0x96, 0x09, 0xcd, 0xcd, 0xda, 0x1b, 0xef, 0xfd,
	0x2f, 0x0b, 0x6c, 0x7d, 0xfd, 0xc8, 0x81, 0xda, 0xd5, 0x38, 0x1c, 0xf6, 0xa6, 0x43, 0xef, 0x19,
	0x02, 0xb0, 0xa7, 0xc3, 0x5e, 0xf7, 0xe4, 0xd4, 0xb3, 0x8c, 0x7d, 0x72, 0xd4, 0xf5, 0xb6, 0x90,
	0x0b, 0x8d, 0xf3, 0xb3, 0xc1, 0xa0, 0x77, 0x2e, 0x43, 0x15, 0xe9, 0xe2, 0xd1, 0xe4, 0xec, 0xf2,
	0xeb, 0xd1, 0xe9, 0x27, 0xaf, 0x2a, 0x25, 0xfa, 0xa3, 0xeb, 0xc1, 0x78, 0x74, 0xe5, 0x6d, 0xa3,
	0x26, 0x80, 0x4e, 0x0b, 0x25, 0xd7, 0x46, 0x2d, 0x70, 0xfa, 0x17, 0xbd, 0xf3, 0xb3, 0x6e, 0x3f,
	0x94, 0x5a, 0xb5, 0x47, 0x60, 0xaa, 0x18, 0x75, 0x59, 0x48, 0x01, 0xc7, 0x5e, 0xa3, 0xef, 0xdc,
	0x34, 0x1e, 0x4e, 0x33, 0xb3, 0xd5, 0xcf, 0xea, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0xb7, 0xa4, 0x44, 0xc4, 0x04, 0x00, 0x00,
}
