// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/ibc/lightclients/zkp/v1/long.proto

package _5_long

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Height struct {
	// the revision that the client is currently on
	RevisionNumber uint64 `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	// the height within the given revision
	RevisionHeight       uint64   `protobuf:"varint,2,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Height) Reset()         { *m = Height{} }
func (m *Height) String() string { return proto.CompactTextString(m) }
func (*Height) ProtoMessage()    {}
func (*Height) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4e19137f971f15, []int{0}
}
func (m *Height) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Height.Unmarshal(m, b)
}
func (m *Height) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Height.Marshal(b, m, deterministic)
}
func (m *Height) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Height.Merge(m, src)
}
func (m *Height) XXX_Size() int {
	return xxx_messageInfo_Height.Size(m)
}
func (m *Height) XXX_DiscardUnknown() {
	xxx_messageInfo_Height.DiscardUnknown(m)
}

var xxx_messageInfo_Height proto.InternalMessageInfo

type ClientState struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	LatestHeight         Height   `protobuf:"bytes,2,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4e19137f971f15, []int{1}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientState.Unmarshal(m, b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return xxx_messageInfo_ClientState.Size(m)
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

type MerkleRoot struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerkleRoot) Reset()         { *m = MerkleRoot{} }
func (m *MerkleRoot) String() string { return proto.CompactTextString(m) }
func (*MerkleRoot) ProtoMessage()    {}
func (*MerkleRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4e19137f971f15, []int{2}
}
func (m *MerkleRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerkleRoot.Unmarshal(m, b)
}
func (m *MerkleRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerkleRoot.Marshal(b, m, deterministic)
}
func (m *MerkleRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleRoot.Merge(m, src)
}
func (m *MerkleRoot) XXX_Size() int {
	return xxx_messageInfo_MerkleRoot.Size(m)
}
func (m *MerkleRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleRoot.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleRoot proto.InternalMessageInfo

type ConsensusState struct {
	Root                 MerkleRoot `protobuf:"bytes,2,opt,name=root,proto3" json:"root"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4e19137f971f15, []int{3}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusState.Unmarshal(m, b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return xxx_messageInfo_ConsensusState.Size(m)
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Height)(nil), "ibc.lightclients.zkp.v1.Height")
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.zkp.v1.ClientState")
	proto.RegisterType((*MerkleRoot)(nil), "ibc.lightclients.zkp.v1.MerkleRoot")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.zkp.v1.ConsensusState")
}

func init() {
	proto.RegisterFile("proto/ibc/lightclients/zkp/v1/long.proto", fileDescriptor_2b4e19137f971f15)
}

var fileDescriptor_2b4e19137f971f15 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4c, 0x4a, 0xd6, 0xcf, 0xc9, 0x4c, 0xcf, 0x28, 0x49, 0xce, 0xc9, 0x4c, 0xcd,
	0x2b, 0x29, 0xd6, 0xaf, 0xca, 0x2e, 0xd0, 0x2f, 0x33, 0xd4, 0xcf, 0xc9, 0xcf, 0x4b, 0xd7, 0x03,
	0x2b, 0x11, 0x12, 0xcf, 0x4c, 0x4a, 0xd6, 0x43, 0x56, 0xa3, 0x57, 0x95, 0x5d, 0xa0, 0x57, 0x66,
	0x28, 0x45, 0xc0, 0x88, 0xf4, 0xfc, 0xf4, 0x7c, 0x88, 0x11, 0x4a, 0x09, 0x5c, 0x6c, 0x1e, 0xa9,
	0x20, 0x25, 0x42, 0xea, 0x5c, 0xfc, 0x45, 0xa9, 0x65, 0x99, 0xc5, 0x99, 0xf9, 0x79, 0xf1, 0x79,
	0xa5, 0xb9, 0x49, 0xa9, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x7c, 0x30, 0x61, 0x3f,
	0xb0, 0x28, 0x8a, 0xc2, 0x0c, 0xb0, 0x5e, 0x09, 0x26, 0x54, 0x85, 0x10, 0x13, 0xad, 0x58, 0x3a,
	0x16, 0xc8, 0x33, 0x28, 0x55, 0x71, 0x71, 0x3b, 0x83, 0xad, 0x0f, 0x2e, 0x49, 0x2c, 0x49, 0x15,
	0x92, 0xe4, 0xe2, 0x48, 0xce, 0x48, 0xcc, 0xcc, 0x8b, 0xcf, 0x4c, 0x01, 0x9b, 0xcf, 0x19, 0xc4,
	0x0e, 0xe6, 0x7b, 0xa6, 0x08, 0x79, 0x71, 0xf1, 0xe6, 0x24, 0x96, 0xa4, 0x16, 0x97, 0x20, 0x1b,
	0xcb, 0x6d, 0x24, 0xaf, 0x87, 0xc3, 0x9b, 0x7a, 0x10, 0x7b, 0x9c, 0x58, 0x4e, 0xdc, 0x93, 0x67,
	0x08, 0xe2, 0x81, 0xe8, 0x45, 0xb1, 0x5b, 0x8d, 0x8b, 0xcb, 0x37, 0xb5, 0x28, 0x3b, 0x27, 0x35,
	0x28, 0x3f, 0xbf, 0x44, 0x48, 0x88, 0x8b, 0x25, 0x23, 0xb1, 0x38, 0x03, 0x6c, 0x2d, 0x4f, 0x10,
	0x98, 0x0d, 0x55, 0x17, 0xca, 0xc5, 0xe7, 0x9c, 0x9f, 0x57, 0x9c, 0x9a, 0x57, 0x5c, 0x5a, 0x0c,
	0x71, 0xa6, 0x2d, 0x17, 0x4b, 0x51, 0x7e, 0x3e, 0xcc, 0x09, 0xca, 0x38, 0x9d, 0x80, 0x30, 0x1e,
	0xea, 0x0c, 0xb0, 0x36, 0x88, 0xb1, 0x4e, 0xea, 0x51, 0xaa, 0xb9, 0xf9, 0x29, 0xa5, 0x39, 0xa9,
	0xc5, 0x90, 0x68, 0xd0, 0x85, 0xc5, 0x83, 0x81, 0xa9, 0x2e, 0x28, 0x1a, 0xad, 0xe3, 0x4d, 0xe3,
	0x41, 0x74, 0x12, 0x1b, 0x38, 0x32, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x41, 0xfa,
	0x49, 0xfb, 0x01, 0x00, 0x00,
}
